[package]
name = "client"
version = "0.1.0"
authors = ["bakape <scorpid33@gmail.com>"]

[dependencies]
libc = "0.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[profile.release]
opt-level = 'z'
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
